@mainUrl = http://localhost:3000

###
# 
POST {{mainUrl}}/kanban/add-new-list
content-type: application/json

{
    "name": "test"
}

###
# 
DELETE {{mainUrl}}/kanban/delete-list
content-type: application/json

{
    "id": "1"
}

###
#
GET {{mainUrl}}/test
